In [3]:
import numpy as np
import pandas as pd

In [4]:
data = {
    "name": ["Amit", "Riya", "Karan", "Neha"],
    "age": [25, 28, 30, 26],
    "salary": [40000, 50000, 55000, 45000],
    "city": ["Delhi", "Mumbai", "Bangalore", "Chennai"]
}
pd.DataFrame(data)

    name  age  salary       city
0   Amit   25   40000      Delhi
1   Riya   28   50000     Mumbai
2  Karan   30   55000  Bangalore
3   Neha   26   45000    Chennai

In [5]:
dataList = [['Amit', 25, 40000, 'Delhi'],
 ['Riya', 28, 50000, 'Mumbai'],
 ['Karan', 30, 55000, 'Bangalore'],
 ['Neha', 26, 45000, 'Chennai']]
pd.DataFrame(dataList)

       0   1      2          3
0   Amit  25  40000      Delhi
1   Riya  28  50000     Mumbai
2  Karan  30  55000  Bangalore
3   Neha  26  45000    Chennai

In [7]:
columns = ['Name', 'Age','Salary' , 'City']
df2 = pd.DataFrame(dataList, columns=columns)
df2

    Name  Age  Salary       City
0   Amit   25   40000      Delhi
1   Riya   28   50000     Mumbai
2  Karan   30   55000  Bangalore
3   Neha   26   45000    Chennai

In [8]:
df2[['Name','Age']]

    Name  Age
0   Amit   25
1   Riya   28
2  Karan   30
3   Neha   26

In [10]:
df2['Designation'] = ['doctor','eng','teach','stud']

In [11]:
df2

    Name  Age  Salary       City Designation
0   Amit   25   40000      Delhi      doctor
1   Riya   28   50000     Mumbai         eng
2  Karan   30   55000  Bangalore       teach
3   Neha   26   45000    Chennai        stud

In [12]:
df2.drop('Designation',axis=1)

    Name  Age  Salary       City
0   Amit   25   40000      Delhi
1   Riya   28   50000     Mumbai
2  Karan   30   55000  Bangalore
3   Neha   26   45000    Chennai

In [13]:
df2

    Name  Age  Salary       City Designation
0   Amit   25   40000      Delhi      doctor
1   Riya   28   50000     Mumbai         eng
2  Karan   30   55000  Bangalore       teach
3   Neha   26   45000    Chennai        stud

In [15]:
df2.drop('Designation',axis=1,inplace = True)

In [16]:
df2

    Name  Age  Salary       City
0   Amit   25   40000      Delhi
1   Riya   28   50000     Mumbai
2  Karan   30   55000  Bangalore
3   Neha   26   45000    Chennai

In [18]:
df2.loc[0]

Name       Amit
Age          25
Salary    40000
City      Delhi
Name: 0, dtype: object

In [20]:
df2.loc[[0,1]]

   Name  Age  Salary    City
0  Amit   25   40000   Delhi
1  Riya   28   50000  Mumbai

In [22]:
df2.loc[[0,1]][['Salary','City']]

   Salary    City
0   40000   Delhi
1   50000  Mumbai

In [23]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Karan   30
3   Neha   26

In [25]:
df2[df2['Age'] > 20]

    Name  Age  Salary       City
0   Amit   25   40000      Delhi
1   Riya   28   50000     Mumbai
2  Karan   30   55000  Bangalore
3   Neha   26   45000    Chennai

In [27]:
df2[(df2['Age'] > 20) & (df2['City'] == 'Delhi')]

   Name  Age  Salary   City
0  Amit   25   40000  Delhi