In [1]:
import numpy as np 
import pandas as pd

In [6]:
d= {
    "name": ["Amit", "Riya", "Karan", np.nan],
    "age": [np.nan, np.nan, 30, 26],
    "salary": [40000, 50000,np.nan, 45000],
    "city": ["Delhi", "Mumbai",np.nan, "Chennai"]
}
df = pd.DataFrame(d)

In [7]:
df

    name   age   salary     city
0   Amit   NaN  40000.0    Delhi
1   Riya   NaN  50000.0   Mumbai
2  Karan  30.0      NaN      NaN
3    NaN  26.0  45000.0  Chennai

In [9]:
df.isna().sum()

name      1
age       2
salary    1
city      1
dtype: int64

In [10]:
df.isna().any()

name      True
age       True
salary    True
city      True
dtype: bool

In [12]:
df.dropna()

Empty DataFrame
Columns: [name, age, salary, city]
Index: []

In [13]:
df.dropna(thresh=3)

   name   age   salary     city
0  Amit   NaN  40000.0    Delhi
1  Riya   NaN  50000.0   Mumbai
3   NaN  26.0  45000.0  Chennai

In [14]:
df

    name   age   salary     city
0   Amit   NaN  40000.0    Delhi
1   Riya   NaN  50000.0   Mumbai
2  Karan  30.0      NaN      NaN
3    NaN  26.0  45000.0  Chennai

In [16]:
df.fillna(0)

    name   age   salary     city
0   Amit   0.0  40000.0    Delhi
1   Riya   0.0  50000.0   Mumbai
2  Karan  30.0      0.0        0
3      0  26.0  45000.0  Chennai

In [18]:
values = {'name':10,'age':20,'salary':30,'city':40}
df.fillna(value=values)

    name   age   salary     city
0   Amit  20.0  40000.0    Delhi
1   Riya  20.0  50000.0   Mumbai
2  Karan  30.0     30.0       40
3     10  26.0  45000.0  Chennai