In [3]:
import numpy as np 
import pandas as pd

In [4]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
              'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint (10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df = pd.DataFrame(data)
df ['Month'] = df['Date'].dt.month_name()
df ['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [5]:
pd.pivot_table(df,values='Sales',index = 'Region', columns='Product')

Product      A      B      C      D
Region
East     545.8    NaN    NaN    NaN
North      NaN    NaN  493.2    NaN
South      NaN    NaN    NaN  466.8
West       NaN  596.8    NaN    NaN

In [6]:
pd.pivot_table(df,values='Sales',index = 'Region', columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     610.0    NaN    NaN    NaN
North      NaN    NaN  521.0    NaN
South      NaN    NaN    NaN  484.0
West       NaN  663.0    NaN    NaN

In [7]:
pd.pivot_table(df,values=['Sales','Units'],index = 'Region', columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     545.8    NaN    NaN    NaN  46.4   NaN   NaN   NaN
North      NaN    NaN  493.2    NaN   NaN   NaN  53.6   NaN
South      NaN    NaN    NaN  466.8   NaN   NaN   NaN  51.0
West       NaN  596.8    NaN    NaN   NaN  51.2   NaN   NaN

In [9]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0